// <auto-generated />
using System;
using BlazorWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130081108_AddMoreSampleData")]
    partial class AddMoreSampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorWebApp.Models.SampleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SampleDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Ali Yılmaz",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Emlak Konut",
                            Date = new DateTime(2026, 1, 25, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3020),
                            Description = "Merkez şube konut satışı",
                            Name = "Konut Projesi A",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Alpha",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 1250000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Fatma Demir",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Vestel A.Ş.",
                            Date = new DateTime(2026, 1, 20, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3060),
                            Description = "Ankara şube ofis kiralama",
                            Name = "Ofis Bloğu B",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "İç Anadolu",
                            Status = "Active",
                            Value = 850000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Mehmet Can",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Rönesans Holding",
                            Date = new DateTime(2025, 12, 30, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3060),
                            Description = "İzmir AVM projesi tamamlandı",
                            Name = "AVM Projesi C",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Beta",
                            Region = "Ege",
                            Status = "Inactive",
                            Value = 5000000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            AssignedTo = "Ayşe Kaya",
                            Branch = "Antalya",
                            Category = "Lüks Konut",
                            Customer = "Bireysel Yatırımcı",
                            Date = new DateTime(2025, 11, 30, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3070),
                            Description = "Antalya lüks villa projesi",
                            Name = "Villa Etap 1",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Gamma",
                            Region = "Akdeniz",
                            Status = "Active",
                            Value = 3200000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 5,
                            AssignedTo = "Caner Öz",
                            Branch = "Kocaeli",
                            Category = "Sanayi",
                            Customer = "DHL Express",
                            Date = new DateTime(2026, 1, 15, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3070),
                            Description = "Kocaeli lojistik depo depo inşaatı",
                            Name = "Lojistik Merkezi",
                            PaymentStatus = "Paid",
                            Priority = "Medium",
                            Project = "Beta",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 4500000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 6,
                            AssignedTo = "Deniz Akça",
                            Branch = "Bursa",
                            Category = "Kamu",
                            Customer = "Sağlık Bakanlığı",
                            Date = new DateTime(2026, 1, 10, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3080),
                            Description = "Bursa şehir hastanesi ek bina",
                            Name = "Hastane Projesi",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Delta",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 12000000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 7,
                            AssignedTo = "Selin Ak",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Ağaoğlu",
                            Date = new DateTime(2026, 1, 27, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3080),
                            Description = "Lüks rezidans satışı",
                            Name = "Rezidans X",
                            PaymentStatus = "Paid",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 2500000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 8,
                            AssignedTo = "Emre Aydın",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Kuzu Grup",
                            Date = new DateTime(2026, 1, 23, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3080),
                            Description = "Modern iş merkezi kiralama",
                            Name = "İş Merkezi Y",
                            PaymentStatus = "Pending",
                            Priority = "High",
                            Project = "Beta",
                            Region = "İç Anadolu",
                            Status = "Active",
                            Value = 1800000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 9,
                            AssignedTo = "Zeynep Koç",
                            Branch = "Kocaeli",
                            Category = "Sanayi",
                            Customer = "Trendyol",
                            Date = new DateTime(2025, 12, 30, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3080),
                            Description = "Lojistik depo genişletme",
                            Name = "Depo Z",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Gamma",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 3200000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            AssignedTo = "Hakan Yıldız",
                            Branch = "Bursa",
                            Category = "İnşaat",
                            Customer = "Sur Yapı",
                            Date = new DateTime(2026, 1, 18, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3090),
                            Description = "Yeni etap konut projesi",
                            Name = "Konut Sitesi D",
                            PaymentStatus = "Paid",
                            Priority = "Medium",
                            Project = "Delta",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 4100000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 11,
                            AssignedTo = "Merve Şahin",
                            Branch = "Antalya",
                            Category = "Turizm",
                            Customer = "Hilton",
                            Date = new DateTime(2025, 10, 30, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3110),
                            Description = "5 yıldızlı otel inşaatı",
                            Name = "Otel Projesi E",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Gamma",
                            Region = "Akdeniz",
                            Status = "Active",
                            Value = 15000000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 12,
                            AssignedTo = "Murat Demir",
                            Branch = "İstanbul",
                            Category = "Kamu",
                            Customer = "İBB",
                            Date = new DateTime(2026, 1, 26, 11, 11, 7, 958, DateTimeKind.Local).AddTicks(3110),
                            Description = "Şehir parkı yenileme çalışması",
                            Name = "Park Revizyonu",
                            PaymentStatus = "Paid",
                            Priority = "Low",
                            Project = "Alpha",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 500000m,
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
