// <auto-generated />
using System;
using BlazorWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203104816_UpdateSeedDataToSuedaAkca")]
    partial class UpdateSeedDataToSuedaAkca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorWebApp.Models.SampleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SampleDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Emlak Konut",
                            Date = new DateTime(2026, 1, 29, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6360),
                            Description = "Merkez şube konut satışı",
                            Name = "Konut Projesi A",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Alpha",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 1250000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Fatma Demir",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Vestel A.Ş.",
                            Date = new DateTime(2026, 1, 24, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6400),
                            Description = "Ankara şube ofis kiralama",
                            Name = "Ofis Bloğu B",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "İç Anadolu",
                            Status = "Active",
                            Value = 850000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Mehmet Can",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Rönesans Holding",
                            Date = new DateTime(2026, 1, 3, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6400),
                            Description = "İzmir AVM projesi tamamlandı",
                            Name = "AVM Projesi C",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Beta",
                            Region = "Ege",
                            Status = "Inactive",
                            Value = 5000000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            AssignedTo = "Ayşe Kaya",
                            Branch = "Antalya",
                            Category = "Lüks Konut",
                            Customer = "Bireysel Yatırımcı",
                            Date = new DateTime(2025, 12, 3, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6410),
                            Description = "Antalya lüks villa projesi",
                            Name = "Villa Etap 1",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Gamma",
                            Region = "Akdeniz",
                            Status = "Active",
                            Value = 3200000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 5,
                            AssignedTo = "Caner Öz",
                            Branch = "Kocaeli",
                            Category = "Sanayi",
                            Customer = "DHL Express",
                            Date = new DateTime(2026, 1, 19, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6410),
                            Description = "Kocaeli lojistik depo depo inşaatı",
                            Name = "Lojistik Merkezi",
                            PaymentStatus = "Paid",
                            Priority = "Medium",
                            Project = "Beta",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 4500000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 6,
                            AssignedTo = "Deniz Akça",
                            Branch = "Bursa",
                            Category = "Kamu",
                            Customer = "Sağlık Bakanlığı",
                            Date = new DateTime(2026, 1, 14, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6410),
                            Description = "Bursa şehir hastanesi ek bina",
                            Name = "Hastane Projesi",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Delta",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 12000000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 7,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Ağaoğlu",
                            Date = new DateTime(2026, 1, 31, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6410),
                            Description = "Lüks rezidans satışı",
                            Name = "Rezidans X",
                            PaymentStatus = "Paid",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 2500000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 8,
                            AssignedTo = "Emre Aydın",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Kuzu Grup",
                            Date = new DateTime(2026, 1, 27, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6420),
                            Description = "Modern iş merkezi kiralama",
                            Name = "İş Merkezi Y",
                            PaymentStatus = "Pending",
                            Priority = "High",
                            Project = "Beta",
                            Region = "İç Anadolu",
                            Status = "Active",
                            Value = 1800000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 9,
                            AssignedTo = "Zeynep Koç",
                            Branch = "Kocaeli",
                            Category = "Sanayi",
                            Customer = "Trendyol",
                            Date = new DateTime(2026, 1, 3, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6420),
                            Description = "Lojistik depo genişletme",
                            Name = "Depo Z",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Gamma",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 3200000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            AssignedTo = "Hakan Yıldız",
                            Branch = "Bursa",
                            Category = "İnşaat",
                            Customer = "Sur Yapı",
                            Date = new DateTime(2026, 1, 22, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6420),
                            Description = "Yeni etap konut projesi",
                            Name = "Konut Sitesi D",
                            PaymentStatus = "Paid",
                            Priority = "Medium",
                            Project = "Delta",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 4100000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 11,
                            AssignedTo = "Merve Şahin",
                            Branch = "Antalya",
                            Category = "Turizm",
                            Customer = "Hilton",
                            Date = new DateTime(2025, 11, 3, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6430),
                            Description = "5 yıldızlı otel inşaatı",
                            Name = "Otel Projesi E",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Gamma",
                            Region = "Akdeniz",
                            Status = "Active",
                            Value = 15000000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 12,
                            AssignedTo = "Murat Demir",
                            Branch = "İstanbul",
                            Category = "Kamu",
                            Customer = "İBB",
                            Date = new DateTime(2026, 1, 30, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6430),
                            Description = "Şehir parkı yenileme çalışması",
                            Name = "Park Revizyonu",
                            PaymentStatus = "Paid",
                            Priority = "Low",
                            Project = "Alpha",
                            Region = "Marmara",
                            Status = "Active",
                            Value = 500000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 13,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 3",
                            Date = new DateTime(2026, 1, 21, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6480),
                            Description = "Açıklama metni 13",
                            Name = "Örnek Proje 13",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Beta",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 1300000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 14,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 4",
                            Date = new DateTime(2026, 1, 20, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6500),
                            Description = "Açıklama metni 14",
                            Name = "Örnek Proje 14",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Gamma",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 1400000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 15,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 5",
                            Date = new DateTime(2026, 1, 19, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6530),
                            Description = "Açıklama metni 15",
                            Name = "Örnek Proje 15",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Delta",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 1500000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 16,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 6",
                            Date = new DateTime(2026, 1, 18, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6540),
                            Description = "Açıklama metni 16",
                            Name = "Örnek Proje 16",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 1600000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 17,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 7",
                            Date = new DateTime(2026, 1, 17, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6550),
                            Description = "Açıklama metni 17",
                            Name = "Örnek Proje 17",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Beta",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 1700000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 18,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 8",
                            Date = new DateTime(2026, 1, 16, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6560),
                            Description = "Açıklama metni 18",
                            Name = "Örnek Proje 18",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Gamma",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 1800000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 19,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 9",
                            Date = new DateTime(2026, 1, 15, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6620),
                            Description = "Açıklama metni 19",
                            Name = "Örnek Proje 19",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Delta",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 1900000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 20,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 0",
                            Date = new DateTime(2026, 1, 14, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6630),
                            Description = "Açıklama metni 20",
                            Name = "Örnek Proje 20",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Alpha",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 2000000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 21,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 1",
                            Date = new DateTime(2026, 1, 13, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6640),
                            Description = "Açıklama metni 21",
                            Name = "Örnek Proje 21",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Beta",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 2100000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 22,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 2",
                            Date = new DateTime(2026, 1, 12, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6650),
                            Description = "Açıklama metni 22",
                            Name = "Örnek Proje 22",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Gamma",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 2200000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 23,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 3",
                            Date = new DateTime(2026, 1, 11, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6660),
                            Description = "Açıklama metni 23",
                            Name = "Örnek Proje 23",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Delta",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 2300000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 24,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 4",
                            Date = new DateTime(2026, 1, 10, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6670),
                            Description = "Açıklama metni 24",
                            Name = "Örnek Proje 24",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Alpha",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 2400000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 25,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 5",
                            Date = new DateTime(2026, 1, 9, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6680),
                            Description = "Açıklama metni 25",
                            Name = "Örnek Proje 25",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Beta",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 2500000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 26,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 6",
                            Date = new DateTime(2026, 1, 8, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6690),
                            Description = "Açıklama metni 26",
                            Name = "Örnek Proje 26",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Gamma",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 2600000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 27,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 7",
                            Date = new DateTime(2026, 1, 7, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6700),
                            Description = "Açıklama metni 27",
                            Name = "Örnek Proje 27",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Delta",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 2700000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 28,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 8",
                            Date = new DateTime(2026, 1, 6, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6710),
                            Description = "Açıklama metni 28",
                            Name = "Örnek Proje 28",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 2800000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 29,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 9",
                            Date = new DateTime(2026, 1, 5, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6730),
                            Description = "Açıklama metni 29",
                            Name = "Örnek Proje 29",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Beta",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 2900000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 30,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 0",
                            Date = new DateTime(2026, 1, 4, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6740),
                            Description = "Açıklama metni 30",
                            Name = "Örnek Proje 30",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Gamma",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 3000000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 31,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 1",
                            Date = new DateTime(2026, 1, 3, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6750),
                            Description = "Açıklama metni 31",
                            Name = "Örnek Proje 31",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Delta",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 3100000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 32,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 2",
                            Date = new DateTime(2026, 1, 2, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6760),
                            Description = "Açıklama metni 32",
                            Name = "Örnek Proje 32",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Alpha",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 3200000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 33,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 3",
                            Date = new DateTime(2026, 1, 1, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6770),
                            Description = "Açıklama metni 33",
                            Name = "Örnek Proje 33",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Beta",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 3300000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 34,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 4",
                            Date = new DateTime(2025, 12, 31, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6780),
                            Description = "Açıklama metni 34",
                            Name = "Örnek Proje 34",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Gamma",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 3400000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 35,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 5",
                            Date = new DateTime(2025, 12, 30, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6790),
                            Description = "Açıklama metni 35",
                            Name = "Örnek Proje 35",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Delta",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 3500000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 36,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 6",
                            Date = new DateTime(2025, 12, 29, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6800),
                            Description = "Açıklama metni 36",
                            Name = "Örnek Proje 36",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Alpha",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 3600000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 37,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 7",
                            Date = new DateTime(2025, 12, 28, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6810),
                            Description = "Açıklama metni 37",
                            Name = "Örnek Proje 37",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Beta",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 3700000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 38,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 8",
                            Date = new DateTime(2025, 12, 27, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6820),
                            Description = "Açıklama metni 38",
                            Name = "Örnek Proje 38",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Gamma",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 3800000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 39,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 9",
                            Date = new DateTime(2025, 12, 26, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6830),
                            Description = "Açıklama metni 39",
                            Name = "Örnek Proje 39",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Delta",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 3900000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 40,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 0",
                            Date = new DateTime(2025, 12, 25, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6840),
                            Description = "Açıklama metni 40",
                            Name = "Örnek Proje 40",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 4000000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 41,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 1",
                            Date = new DateTime(2025, 12, 24, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6850),
                            Description = "Açıklama metni 41",
                            Name = "Örnek Proje 41",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Beta",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 4100000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 42,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 2",
                            Date = new DateTime(2025, 12, 23, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6860),
                            Description = "Açıklama metni 42",
                            Name = "Örnek Proje 42",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Gamma",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 4200000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 43,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 3",
                            Date = new DateTime(2025, 12, 22, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6880),
                            Description = "Açıklama metni 43",
                            Name = "Örnek Proje 43",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Delta",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 4300000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 44,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 4",
                            Date = new DateTime(2025, 12, 21, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6890),
                            Description = "Açıklama metni 44",
                            Name = "Örnek Proje 44",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Alpha",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 4400000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 45,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 5",
                            Date = new DateTime(2025, 12, 20, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6900),
                            Description = "Açıklama metni 45",
                            Name = "Örnek Proje 45",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Beta",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 4500000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 46,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 6",
                            Date = new DateTime(2025, 12, 19, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6910),
                            Description = "Açıklama metni 46",
                            Name = "Örnek Proje 46",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Gamma",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 4600000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 47,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 7",
                            Date = new DateTime(2025, 12, 18, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6920),
                            Description = "Açıklama metni 47",
                            Name = "Örnek Proje 47",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Delta",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 4700000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 48,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 8",
                            Date = new DateTime(2025, 12, 17, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6930),
                            Description = "Açıklama metni 48",
                            Name = "Örnek Proje 48",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Alpha",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 4800000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 49,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 9",
                            Date = new DateTime(2025, 12, 16, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6940),
                            Description = "Açıklama metni 49",
                            Name = "Örnek Proje 49",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Beta",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 4900000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 50,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 0",
                            Date = new DateTime(2025, 12, 15, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6950),
                            Description = "Açıklama metni 50",
                            Name = "Örnek Proje 50",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Gamma",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 5000000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 51,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 1",
                            Date = new DateTime(2025, 12, 14, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6960),
                            Description = "Açıklama metni 51",
                            Name = "Örnek Proje 51",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Delta",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 5100000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 52,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 2",
                            Date = new DateTime(2025, 12, 13, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6980),
                            Description = "Açıklama metni 52",
                            Name = "Örnek Proje 52",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 5200000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 53,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 3",
                            Date = new DateTime(2025, 12, 12, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(6990),
                            Description = "Açıklama metni 53",
                            Name = "Örnek Proje 53",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Beta",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 5300000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 54,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 4",
                            Date = new DateTime(2025, 12, 11, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7000),
                            Description = "Açıklama metni 54",
                            Name = "Örnek Proje 54",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Gamma",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 5400000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 55,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 5",
                            Date = new DateTime(2025, 12, 10, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7010),
                            Description = "Açıklama metni 55",
                            Name = "Örnek Proje 55",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Delta",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 5500000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 56,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 6",
                            Date = new DateTime(2025, 12, 9, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7020),
                            Description = "Açıklama metni 56",
                            Name = "Örnek Proje 56",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Alpha",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 5600000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 57,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 7",
                            Date = new DateTime(2025, 12, 8, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7030),
                            Description = "Açıklama metni 57",
                            Name = "Örnek Proje 57",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Beta",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 5700000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 58,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 8",
                            Date = new DateTime(2025, 12, 7, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7040),
                            Description = "Açıklama metni 58",
                            Name = "Örnek Proje 58",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Gamma",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 5800000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 59,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 9",
                            Date = new DateTime(2025, 12, 6, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7050),
                            Description = "Açıklama metni 59",
                            Name = "Örnek Proje 59",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Delta",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 5900000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 60,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 0",
                            Date = new DateTime(2025, 12, 5, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7060),
                            Description = "Açıklama metni 60",
                            Name = "Örnek Proje 60",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Alpha",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 6000000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 61,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 1",
                            Date = new DateTime(2025, 12, 4, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7070),
                            Description = "Açıklama metni 61",
                            Name = "Örnek Proje 61",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Beta",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 6100000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 62,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 2",
                            Date = new DateTime(2025, 12, 3, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7080),
                            Description = "Açıklama metni 62",
                            Name = "Örnek Proje 62",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Gamma",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 6200000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 63,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 3",
                            Date = new DateTime(2025, 12, 2, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7090),
                            Description = "Açıklama metni 63",
                            Name = "Örnek Proje 63",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Delta",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 6300000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 64,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 4",
                            Date = new DateTime(2025, 12, 1, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7100),
                            Description = "Açıklama metni 64",
                            Name = "Örnek Proje 64",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 6400000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 65,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 5",
                            Date = new DateTime(2025, 11, 30, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7110),
                            Description = "Açıklama metni 65",
                            Name = "Örnek Proje 65",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Beta",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 6500000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 66,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 6",
                            Date = new DateTime(2025, 11, 29, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7120),
                            Description = "Açıklama metni 66",
                            Name = "Örnek Proje 66",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Gamma",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 6600000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 67,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 7",
                            Date = new DateTime(2025, 11, 28, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7130),
                            Description = "Açıklama metni 67",
                            Name = "Örnek Proje 67",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Delta",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 6700000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 68,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 8",
                            Date = new DateTime(2025, 11, 27, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7140),
                            Description = "Açıklama metni 68",
                            Name = "Örnek Proje 68",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Alpha",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 6800000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 69,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 9",
                            Date = new DateTime(2025, 11, 26, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7150),
                            Description = "Açıklama metni 69",
                            Name = "Örnek Proje 69",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Beta",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 6900000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 70,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 0",
                            Date = new DateTime(2025, 11, 25, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7160),
                            Description = "Açıklama metni 70",
                            Name = "Örnek Proje 70",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Gamma",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 7000000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 71,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 1",
                            Date = new DateTime(2025, 11, 24, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7220),
                            Description = "Açıklama metni 71",
                            Name = "Örnek Proje 71",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Delta",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 7100000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 72,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 2",
                            Date = new DateTime(2025, 11, 23, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7230),
                            Description = "Açıklama metni 72",
                            Name = "Örnek Proje 72",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Alpha",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 7200000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 73,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 3",
                            Date = new DateTime(2025, 11, 22, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7240),
                            Description = "Açıklama metni 73",
                            Name = "Örnek Proje 73",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Beta",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 7300000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 74,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 4",
                            Date = new DateTime(2025, 11, 21, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7250),
                            Description = "Açıklama metni 74",
                            Name = "Örnek Proje 74",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Gamma",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 7400000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 75,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 5",
                            Date = new DateTime(2025, 11, 20, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7260),
                            Description = "Açıklama metni 75",
                            Name = "Örnek Proje 75",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Delta",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 7500000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 76,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 6",
                            Date = new DateTime(2025, 11, 19, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7270),
                            Description = "Açıklama metni 76",
                            Name = "Örnek Proje 76",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 7600000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 77,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 7",
                            Date = new DateTime(2025, 11, 18, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7280),
                            Description = "Açıklama metni 77",
                            Name = "Örnek Proje 77",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Beta",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 7700000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 78,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 8",
                            Date = new DateTime(2025, 11, 17, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7290),
                            Description = "Açıklama metni 78",
                            Name = "Örnek Proje 78",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Gamma",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 7800000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 79,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 9",
                            Date = new DateTime(2025, 11, 16, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7300),
                            Description = "Açıklama metni 79",
                            Name = "Örnek Proje 79",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Delta",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 7900000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 80,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 0",
                            Date = new DateTime(2025, 11, 15, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7310),
                            Description = "Açıklama metni 80",
                            Name = "Örnek Proje 80",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Alpha",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 8000000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 81,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 1",
                            Date = new DateTime(2025, 11, 14, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7320),
                            Description = "Açıklama metni 81",
                            Name = "Örnek Proje 81",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Beta",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 8100000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 82,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 2",
                            Date = new DateTime(2025, 11, 13, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7330),
                            Description = "Açıklama metni 82",
                            Name = "Örnek Proje 82",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Gamma",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 8200000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 83,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 3",
                            Date = new DateTime(2025, 11, 12, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7340),
                            Description = "Açıklama metni 83",
                            Name = "Örnek Proje 83",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Delta",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 8300000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 84,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 4",
                            Date = new DateTime(2025, 11, 11, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7350),
                            Description = "Açıklama metni 84",
                            Name = "Örnek Proje 84",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Alpha",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 8400000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 85,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 5",
                            Date = new DateTime(2025, 11, 10, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7360),
                            Description = "Açıklama metni 85",
                            Name = "Örnek Proje 85",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Beta",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 8500000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 86,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 6",
                            Date = new DateTime(2025, 11, 9, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7370),
                            Description = "Açıklama metni 86",
                            Name = "Örnek Proje 86",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Gamma",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 8600000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 87,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 7",
                            Date = new DateTime(2025, 11, 8, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7380),
                            Description = "Açıklama metni 87",
                            Name = "Örnek Proje 87",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Delta",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 8700000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 88,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 8",
                            Date = new DateTime(2025, 11, 7, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7390),
                            Description = "Açıklama metni 88",
                            Name = "Örnek Proje 88",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 8800000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 89,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 9",
                            Date = new DateTime(2025, 11, 6, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7400),
                            Description = "Açıklama metni 89",
                            Name = "Örnek Proje 89",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Beta",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 8900000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 90,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 0",
                            Date = new DateTime(2025, 11, 5, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7410),
                            Description = "Açıklama metni 90",
                            Name = "Örnek Proje 90",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Gamma",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 9000000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 91,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 1",
                            Date = new DateTime(2025, 11, 4, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7420),
                            Description = "Açıklama metni 91",
                            Name = "Örnek Proje 91",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Delta",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 9100000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 92,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 2",
                            Date = new DateTime(2025, 11, 3, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7430),
                            Description = "Açıklama metni 92",
                            Name = "Örnek Proje 92",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Alpha",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 9200000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 93,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 3",
                            Date = new DateTime(2025, 11, 2, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7440),
                            Description = "Açıklama metni 93",
                            Name = "Örnek Proje 93",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Beta",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 9300000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 94,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 4",
                            Date = new DateTime(2025, 11, 1, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7450),
                            Description = "Açıklama metni 94",
                            Name = "Örnek Proje 94",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Gamma",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 9400000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 95,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "Ticari",
                            Customer = "Müşteri 5",
                            Date = new DateTime(2025, 10, 31, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7460),
                            Description = "Açıklama metni 95",
                            Name = "Örnek Proje 95",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Delta",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 9500000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 96,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Customer = "Müşteri 6",
                            Date = new DateTime(2025, 10, 30, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7470),
                            Description = "Açıklama metni 96",
                            Name = "Örnek Proje 96",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Alpha",
                            Region = "Bölge 1",
                            Status = "Active",
                            Value = 9600000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 97,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "Ticari",
                            Customer = "Müşteri 7",
                            Date = new DateTime(2025, 10, 29, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7480),
                            Description = "Açıklama metni 97",
                            Name = "Örnek Proje 97",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Beta",
                            Region = "Bölge 2",
                            Status = "Active",
                            Value = 9700000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 98,
                            AssignedTo = "Sueda Akça",
                            Branch = "İzmir",
                            Category = "İnşaat",
                            Customer = "Müşteri 8",
                            Date = new DateTime(2025, 10, 28, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7490),
                            Description = "Açıklama metni 98",
                            Name = "Örnek Proje 98",
                            PaymentStatus = "Overdue",
                            Priority = "Low",
                            Project = "Gamma",
                            Region = "Bölge 3",
                            Status = "Active",
                            Value = 9800000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 99,
                            AssignedTo = "Sueda Akça",
                            Branch = "İstanbul",
                            Category = "Ticari",
                            Customer = "Müşteri 9",
                            Date = new DateTime(2025, 10, 27, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7500),
                            Description = "Açıklama metni 99",
                            Name = "Örnek Proje 99",
                            PaymentStatus = "Paid",
                            Priority = "High",
                            Project = "Delta",
                            Region = "Bölge 4",
                            Status = "Active",
                            Value = 9900000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 100,
                            AssignedTo = "Sueda Akça",
                            Branch = "Ankara",
                            Category = "İnşaat",
                            Customer = "Müşteri 0",
                            Date = new DateTime(2025, 10, 26, 13, 48, 16, 768, DateTimeKind.Local).AddTicks(7520),
                            Description = "Açıklama metni 100",
                            Name = "Örnek Proje 100",
                            PaymentStatus = "Pending",
                            Priority = "Medium",
                            Project = "Alpha",
                            Region = "Bölge 0",
                            Status = "Active",
                            Value = 10000000m,
                            Year = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
