// <auto-generated />
using System;
using BlazorWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130063830_UpdateSampleDataModel")]
    partial class UpdateSampleDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorWebApp.Models.SampleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SampleDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Branch = "İstanbul",
                            Category = "İnşaat",
                            Date = new DateTime(2026, 1, 25, 9, 38, 30, 624, DateTimeKind.Local).AddTicks(2720),
                            Description = "Merkez şube konut satışı",
                            Name = "Konut Projesi A",
                            Project = "Alpha",
                            Status = "Active",
                            Value = 1250000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            Branch = "Ankara",
                            Category = "Ticari",
                            Date = new DateTime(2026, 1, 20, 9, 38, 30, 624, DateTimeKind.Local).AddTicks(2770),
                            Description = "Ankara şube ofis kiralama",
                            Name = "Ofis Bloğu B",
                            Project = "Alpha",
                            Status = "Active",
                            Value = 850000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Branch = "İzmir",
                            Category = "Ticari",
                            Date = new DateTime(2025, 12, 30, 9, 38, 30, 624, DateTimeKind.Local).AddTicks(2770),
                            Description = "İzmir AVM projesi tamamlandı",
                            Name = "AVM Projesi C",
                            Project = "Beta",
                            Status = "Inactive",
                            Value = 5000000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            Branch = "Antalya",
                            Category = "Lüks Konut",
                            Date = new DateTime(2025, 11, 30, 9, 38, 30, 624, DateTimeKind.Local).AddTicks(2780),
                            Description = "Antalya lüks villa projesi",
                            Name = "Villa Etap 1",
                            Project = "Gamma",
                            Status = "Active",
                            Value = 3200000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 5,
                            Branch = "Kocaeli",
                            Category = "Sanayi",
                            Date = new DateTime(2026, 1, 15, 9, 38, 30, 624, DateTimeKind.Local).AddTicks(2780),
                            Description = "Kocaeli lojistik depo depo inşaatı",
                            Name = "Lojistik Merkezi",
                            Project = "Beta",
                            Status = "Active",
                            Value = 4500000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 6,
                            Branch = "Bursa",
                            Category = "Kamu",
                            Date = new DateTime(2026, 1, 10, 9, 38, 30, 624, DateTimeKind.Local).AddTicks(2780),
                            Description = "Bursa şehir hastanesi ek bina",
                            Name = "Hastane Projesi",
                            Project = "Delta",
                            Status = "Active",
                            Value = 12000000m,
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
